export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER'
export const GET_LIST_CUSTOMER_SUCCESS = 'GET_LIST_CUSTOMER_SUCCESS'
export const GET_LIST_CUSTOMER_FAILED = 'GET_LIST_CUSTOMER_FAILED'

export const GET_CUSTOMER = 'GET_CUSTOMER'
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'
export const GET_CUSTOMER_FAILED = 'GET_CUSTOMER_FAILED'

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED'

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILED = 'UPDATE_CUSTOMER_FAILED'

export const COPY_CUSTOMER = 'COPY_CUSTOMER'
export const COPY_CUSTOMER_SUCCESS = 'COPY_CUSTOMER_SUCCESS'
export const COPY_CUSTOMER_FAILED = 'COPY_CUSTOMER_FAILED'

export const PUBLISH_CUSTOMER = 'PUBLISH_CUSTOMER'
export const PUBLISH_CUSTOMER_SUCCESS = 'PUBLISH_CUSTOMER_SUCCESS'
export const PUBLISH_CUSTOMER_FAILED = 'PUBLISH_CUSTOMER_FAILED'

export const ARCHIVE_CUSTOMER = 'ARCHIVE_CUSTOMER'
export const ARCHIVE_CUSTOMER_SUCCESS = 'ARCHIVE_CUSTOMER_SUCCESS'
export const ARCHIVE_CUSTOMER_FAILED = 'ARCHIVE_CUSTOMER_FAILED'

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED'
